TVS-LATAM/erpnext

- erpnext/projects/doctype/project/project.json
- erpnext/projects/doctype/project/project.py
> cambios tarea 507

- erpnext/setup/doctype/holiday/holiday.py
Implemented getHolidayList to fetch and return a list of holidays.
> feat: implement function to retrieve holiday list

- erpnext/public/scss/erpnext.bundle.scss
> Fix path for glider css file

- erpnext/projects/doctype/project/project.js
- erpnext/projects/doctype/project/project.json
- erpnext/public/js/glider.bundle.js
> Fix attachments section

- erpnext/projects/doctype/project/project.json
> feat: update remote diagnose time

- erpnext/projects/doctype/project/project.js
> feat(project): button to fetch partslink data with the VIN added

- erpnext/projects/doctype/project/project.js
> fix(project): vin reseted when the search is wrong

- erpnext/projects/doctype/project/project.json
> feat(project): checkbox for test_drive_conditions added

- erpnext/projects/doctype/project/project.json
> feat(project): internal notes adjusted and client notes added

- erpnext/projects/doctype/project/project.json
> Chatbot 790 extra slot time to remote diagnose

- erpnext/projects/doctype/project/project.json
> feat: add check for dongle tested in project doctype

- erpnext/public/scss/erpnext.scss
> fix: update button styles for mobile

- erpnext/projects/doctype/project/project.json
> feat: add field for price agreement in project doctype

- erpnext/projects/doctype/project/project.json
> feat: add field for fixed appointment time

- erpnext/projects/doctype/project/project.json
> feat: update type of jobs options in project doctype

- erpnext/projects/doctype/project/project.js
> Chatbot 842 verify before change to status  quality check approve 

- erpnext/projects/doctype/client_requirements/client_requirements.json
- erpnext/projects/doctype/client_requirements/client_requirements.py
- erpnext/projects/doctype/project/project.js
- erpnext/projects/doctype/project/project.json
> feat: add client requirement section and validate it in dialog

- erpnext/projects/doctype/project/project.json
> feat: add pickup attribute to project doctype

- erpnext/public/scss/erpnext.scss
> fix: add max width to chat container

- erpnext/projects/doctype/project/project.json
> fix: update oilewisse to oliewissel in type of job options

- erpnext/projects/doctype/project/project.json
> feat: add terms and conditions check in project doctype

- package.json
- yarn.lock
> Update quotation component version

- erpnext/projects/doctype/job_workload_item/job_workload_item.json
- erpnext/projects/doctype/job_workload_item/job_workload_item.py
- erpnext/projects/doctype/queue_settings/queue_settings.json
> feat: add table to handle job workload in queue settings doctype

- erpnext/projects/doctype/project/project.json
> feat: update pickup attribute to a dropdown

- erpnext/projects/doctype/project/project.js
> fix: solve issue related with duplicated vin

- erpnext/projects/doctype/project/project.js
> feat: use user_info instead of user instance

- erpnext/projects/doctype/project/project.js
> feat: add listener for translations

- erpnext/public/js/utils/sales_common.js
- erpnext/selling/doctype/quotation/quotation.js
> feat: use rare from price list to ensure discount is apply correctly [Needs Review]

- erpnext/projects/doctype/project/project_list.js
> Chatbot 1013 add a message of warning to the freeze queue positions checkbox

- erpnext/projects/doctype/project/project.js
- erpnext/projects/doctype/project/project.py
> feat: add dialog to send message after remote diagnose

- erpnext/projects/doctype/project/project.js
- erpnext/projects/doctype/project/project.json
> feat: made license plate and customer as required

- erpnext/projects/doctype/project/project.js
- erpnext/public/scss/erpnext.scss
> feat: add buttons to translate diagnose result

- erpnext/projects/doctype/project/project.js
> fix: update previus status when page is load

- erpnext/projects/doctype/queue_settings/queue_settings.js
- erpnext/projects/doctype/queue_settings/queue_settings.json
- erpnext/projects/doctype/queue_settings/queue_settings.py
> Chatbot 457 add a field to change the cars per day parameter

- erpnext/projects/doctype/project/project.js
> feat: show dialog when try to update project to completed and loan car is not paid

- erpnext/projects/doctype/project/project.js
> fix: validate that quotations is not in quality check apporved

- erpnext/projects/doctype/project/project.js
> feat: add button to go to current loan car doctype

- erpnext/setup/doctype/holiday_list/holiday_list.py
> feat: add switch appointment status when holiday is added

- package.json
> fix: update calendar component version

- erpnext/setup/doctype/holiday_list/holiday_list.py
> fox: remove dialogs and update delete_row

- package.json
> chore: update calendar version

- erpnext/projects/doctype/project/project.js
> fix: Close sockets before creation to prevent socket stack issues

- erpnext/projects/doctype/project/project.js
> fix: update loan car button text

- erpnext/accounts/doctype/account/account.json
- erpnext/stock/doctype/item_default/item_default.json
> feat: add provider account id into account doctype

- erpnext/stock/doctype/handle_parts/handle_parts.js
- erpnext/stock/doctype/handle_parts/handle_parts.json
- erpnext/stock/doctype/handle_parts/handle_parts.py
- erpnext/stock/doctype/handle_parts_config/handle_parts_config.json
- erpnext/stock/doctype/item/item.json
- erpnext/stock/doctype/transmission_code_compatibility/transmission_code_compatibility.json
- erpnext/stock/doctype/transmission_code_compatibility/transmission_code_compatibility.py
[CHATBOT-1094]: https://tvsgroup.atlassian.net/browse/CHATBOT-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chatbot 1094 refactor upload file in handle parts
